<?php

/**
 * @file
 * Streetnet stories in code.
 *
 */

function streetnet_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'example') . '/views',
//    'template path' => drupal_get_path('module', 'example') . '/themes',
  );
}

function streetnet_views_default_views() {
  $views = array();
  $files = file_scan_directory( drupal_get_path('module', 'streetnet_stories').'/views', '/\.inc$/' );
  foreach ($files as $filepath => $file) {
    require $filepath;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}
