<?php

/**
 * @file
 * Streetnet custom stuff, exported views, and other sundries.
 *
 */

function streetnet_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'streetnet') . '/views',
//    'template path' => drupal_get_path('module', 'example') . '/themes',
  );
}

function streetnet_views_default_views() {
  $views = array();
  $files = file_scan_directory( drupal_get_path('module', 'streetnet').'/views', '/\.inc$/' );
  foreach ($files as $filepath => $file) {
    require $filepath;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}

/**
 * Implements hook_quicktabs_default_quicktabs().
 */
function streetnet_quicktabs_default_quicktabs() {
  $items = array();
  $files = file_scan_directory( drupal_get_path('module', 'streetnet').'/quicktabs', '/\.inc$/' );
  foreach ($files as $filepath => $file) {
    require $filepath;
      watchdog('streetnet', $quicktabs );
    if (isset($quicktabs)) {
      $items[$quicktabs->machine_name] = $quicktabs;
    }
  }
  return $items;
}
?>